version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    restart: always

  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
