version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: no # Temporarily disable restart for debugging
  backend:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    restart: no # Temporarily disable restart
