version: "3.9"
services:
  backend:
    image: thanhphongkm20/backend:${GITHUB_SHA:-latest}
    env_file:
      - ./env/backend.env
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: thanhphongkm20/frontend:${GITHUB_SHA:-latest}
    env_file:
      - ./env/frontend.env
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend