name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main   

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Pull Backend image
        run: docker pull thanhphongkm20/backend:latest

      - name: Pull Frontend image
        run: docker pull thanhphongkm20/frontend:latest

      - name: Remove old containers
        run: |
          docker rm -f backend-container || true
          docker rm -f frontend-container || true

      - name: Run Backend container
        run: docker run -d --name backend-container -p 5000:5000 \
               -e MONGO_DB="mongodb+srv://thanhphong044756:Tp044756@phongdeptrai.ehcg02t.mongodb.net/phongdeptrai" \
               thanhphongkm20/backend:latest

      - name: Run Frontend container
        run: docker run -d --name frontend-container -p 3000:3000 \
               thanhphongkm20/frontend:latest
