name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint (Backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: Server/node_modules
          key: backend-${{ hashFiles('Server/package-lock.json', 'Server/package.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd Server && npm install
      - run: cd Server && npm run lint -- --ext .js --max-warnings=0

  test:
    name: Test (Backend)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: Server/node_modules
          key: backend-${{ hashFiles('Server/package-lock.json', 'Server/package.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd Server && npm install
      - run: cd Server && npm test

  build:
    name: Build (Frontend - Check Only)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: client/node_modules
          key: frontend-${{ hashFiles('client/package-lock.json', 'client/package.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: cd client && npm install && npm run build

  build-and-deploy:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Free disk space
        run: |
          docker system prune -af --volumes || true
          sudo rm -rf /var/lib/apt/lists/* || true
          sudo apt-get clean || true
          sudo journalctl --vacuum-time=1d || true

      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Frontend Image
        run: |
          cd client
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/frontend
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Build & Push Backend Image
        run: |
          cd Server
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/backend
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

  deploy:
    name: Deploy on EC2
    runs-on: self-hosted
    needs: build-and-deploy
    steps:
      - run: |
          cd /home/ubuntu/actions-runner/_work/cicdgithub

          echo "Pulling latest images..."
          docker-compose pull

          echo "Starting updated containers (zero-downtime)..."
          docker-compose up -d

          echo "Cleaning unused resources..."
          docker system prune -af --volumes || true
