name: Deploy Fullstack App to EC2

on:
  push:
    branches: [main] # sửa theo branch của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          CI=false npm run build

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Upload frontend build
      - name: Upload frontend to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend/build/*"
          target: "/tmp/frontend"

      # Upload backend
      - name: Upload backend to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/*"
          target: "/tmp/backend"

      # SSH deploy script
      - name: SSH deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # FRONTEND
            sudo rm -rf /var/www/html/*
            sudo cp -r /tmp/frontend/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html

            # BACKEND
            sudo rm -rf /var/www/backend
            sudo mkdir -p /var/www/backend
            sudo cp -r /tmp/backend/* /var/www/backend
            cd /var/www/backend
            npm install

            # PM2 restart
            if command -v pm2 > /dev/null; then
              pm2 restart backend || pm2 start index.js --name backend
              pm2 save
            else
              echo "⚠️ PM2 not found!"
            fi

            # Reload nginx
            sudo systemctl reload nginx
